22.03.29 20:52:20 - (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
22.03.29 23:03:26 - (<class 'ValueError'>, None): too many values to unpack (expected 1)
22.03.29 23:04:01 - (<class 'TypeError'>, None): 'int' object is not subscriptable
22.03.29 23:04:40 - (<class 'KeyError'>, None): 'class'
22.03.29 23:14:32 - (<class 'TypeError'>, None): 'int' object is not subscriptable
22.03.30 10:54:23 - (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
22.03.30 10:54:32 - (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
22.03.30 17:37:35 - (<class 'AttributeError'>, None): 'list' object has no attribute 'strip'
22.03.30 17:38:51 - (<class 'AttributeError'>, None): 'map' object has no attribute 'strip'
22.03.30 18:28:05 - (<class 'TypeError'>, None): can't multiply sequence by non-int of type 'NoneType'
22.03.31 17:01:10 - (<class 'KeyError'>, None): 'reason'
22.04.06 00:27:41 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.04.07 21:12:45 - "Bot_polling error: (<class 'AttributeError'>, None): 'NoneType' object has no attribute 'lower'"
22.04.10 20:00:07 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:13 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:19 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:25 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:31 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:37 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:43 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:49 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:00:55 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:00 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:06 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:12 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:18 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:24 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:30 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:35 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:41 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:47 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:53 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:01:59 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:04 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:10 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:16 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:22 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:27 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:33 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:39 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:44 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 20:02:50 - "Schedule error: <class 'AttributeError'> 'int' object has no attribute 'get'"
22.04.10 21:28:11 - "Bot_polling error: (<class 'NameError'>, None): name 'deleted' is not defined"
22.04.20 13:18:16 - "Bot_polling error: (<class 'NameError'>, None): name 'HUMANS' is not defined"
22.05.04 12:17:31 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.05.04 12:17:34 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.05.04 12:17:39 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.05.04 12:17:57 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.05.04 12:18:07 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
22.05.04 12:18:20 - "Bot_polling error: (<class 'telebot.apihelper.ApiTelegramException'>, None): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
24.05.2022 08:01:23 - "Bot_polling error: (<class 'TypeError'>, None): can only concatenate tuple (not "list") to tuple"
24.05.2022 08:01:37 - "Bot_polling error: (<class 'TypeError'>, None): can only concatenate tuple (not "list") to tuple"
